name: sonarCS
env:
  SONAR_ORG: filetrust-2
  SONAR_PROJECT: caf
  
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          submodules: true
          token: ${{ secrets.TOKEN }}
          
      - name: scan java code
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR }}
